In [1]:
import numpy as np
print(np.__version__)


1.19.2


In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
b = np.array([[7.0,6.0,5.0],[4.0,3.0,2.0]])
print(b)

[[7. 6. 5.]
 [4. 3. 2.]]


In [8]:
a.ndim

1

In [9]:
b.ndim

2

In [10]:
a.shape

(5,)

In [11]:
b.shape

(2, 3)

In [13]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [14]:
# Specific Element
a[1,4]

11

In [15]:
# Specific Row
a[0,:]

array([1, 2, 3, 4, 5, 6])

In [16]:
# Specific Column
a[:,5]

array([ 6, 12])

In [19]:
a = np.array ([0,1,2,3,4,5,6,7,8,9,10])
#Even Numbers
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [21]:
a[a % 2 == 1] = -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


In [25]:
 a = np.arange(10)
out = np.where(a%2 == 1, -1, a)
print(a)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [26]:
a = np.arange(10)
a.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
b = ([11,12,13,14,15,16,17,18,19,20])

In [30]:
# Stacking two arrays Vertically Method-1
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.concatenate([a,b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
# Stacking two arrays Vertically Method-2
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [32]:
# Stacking two arrays Horizontally Method-1
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [33]:
# Stacking two arrays Horizontally Method-2
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [36]:
a = np.array([1,2,3,2,3,11,3,4,5,6])
b = np.array([7,3,10,2,7,9,4,9,8,11])
# Common Items
np.intersect1d(a,b)

array([ 2,  3,  4, 11])

In [37]:
# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 5, 6])

In [38]:
# Common Elements
np.where(a == b)

(array([3], dtype=int64),)

In [39]:
# extract all numbers between a given range from a numpy array
a = np.arange(15)
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
b = np.array([[9,8,7,6,5],[4,3,2,1,0]])
# swapping two rows in 2d array
b = np.arange(9).reshape(3,3)
b[[1,0,2], :]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [76]:
# swapping two columns in 2d array
b = np.arange(9).reshape(3,3)
print(b[:, [1,0,2]])

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [75]:
# reversing the rows of a 2D array
b = np.arange(9).reshape(3,3)
print(b[::-1])

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [74]:
# reversing the columns of a 2D array
b = np.arange(9).reshape(3,3)
print(b[:, ::-1])

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [73]:
rand_ar = np.random.random((4,4))
# printing till 3 decimal places of numpy array
np.set_printoptions(precision=3)
print(rand_ar[:3])

[[0.812 0.172 0.816 0.274]
 [0.432 0.94  0.818 0.336]
 [0.175 0.373 0.006 0.252]]


In [71]:
# by suppressing the scientific notation (like 1e10)
np.set_printoptions(suppress=False)
np.random.seed(100)
rand_ar = np.random.random([4,4])/1e3
print(rand_ar)

[[5.434e-04 2.784e-04 4.245e-04 8.448e-04]
 [4.719e-06 1.216e-04 6.707e-04 8.259e-04]
 [1.367e-04 5.751e-04 8.913e-04 2.092e-04]
 [1.853e-04 1.084e-04 2.197e-04 9.786e-04]]


In [72]:
np.random.seed(100)
rand_ar = np.random.random([4,4])
np.set_printoptions(suppress=True, precision=3)
print(rand_ar)

[[0.543 0.278 0.425 0.845]
 [0.005 0.122 0.671 0.826]
 [0.137 0.575 0.891 0.209]
 [0.185 0.108 0.22  0.979]]


In [70]:
# Limit the number of items printed
np.set_printoptions()
a = np.arange(10)
print(a)

[0 1 2 ... 7 8 9]


In [78]:
# Find the mean, median, standard deviation of iris's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


In [80]:
#Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
# or 
S = (sepallength - Smin)/sepallength.ptp() 
print(S)

[0.222 0.167 0.111 ... 0.611 0.528 0.444]


In [89]:
# Find the 10th and 90th percentile of iris's sepallength
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

np.percentile(sepallength, q=[10, 90])

array([4.8, 6.9])

In [94]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [95]:
a + 2

array([3, 4, 5, 6])

In [96]:
a - 2

array([-1,  0,  1,  2])

In [97]:
a * 2

array([2, 4, 6, 8])

In [98]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [99]:
np.cos(a)

array([ 0.54 , -0.416, -0.99 , -0.654])

In [103]:
# find if a given array has any null values
# Returns True/False value elementwise  
b = np.arange(25).reshape(5, 5) 
                 
print("\nIs NaN: \n", np.isnan(b)) 
    
c = [[1,2,3],  
     [np.nan,2,2]] 
print("\nIs NaN: \n", np.isnan(c))


Is NaN: 
 [[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]

Is NaN: 
 [[False False False]
 [ True False False]]


In [105]:
# Replace negative value with zero in numpy array
a_array1 = np.array([1, 2, -3, 4, -5, -6])

print("initial array", a_array1) 
# replace all negative value with 0 
a_array1[a_array1<0] = 0
  
print("New resulting array: ", a_array1) 

initial array [ 1  2 -3  4 -5 -6]
New resulting array:  [1 2 0 4 0 0]


In [107]:
# convert a numeric to a categorical (text) array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Bin petallength 
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# View
petal_length_cat[:4]

['small', 'small', 'small', 'small']

In [108]:
# Linear Algebra
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [109]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [110]:
# Statistics
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
np.min(stats)

1

In [112]:
np.max(stats, axis=1)

array([3, 6])

In [113]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [ ]:
# --- End ---- #